name = "astro-lumphammer"
compatibility_date = "2026-01-04"
main = "dist/_worker.js/index.js"

compatibility_flags= [
  "nodejs_compat",
  "global_fetch_strictly_public"
]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[[kv_namespaces]]
binding = "COUNTER"
id = "fa052c8d3c134446954fc15b730df7d8"
