name = "astro-lumphammer"
compatibility_date = "2026-01-04"
main = "dist/_worker.js/index.js"


compatibility_flags= [
  "nodejs_compat",
  "global_fetch_strictly_public"
]

[assets]
binding = "ASSETS"
directory = "./dist"
html_handling = "drop-trailing-slash"

[observability]
enabled = true
